### ISSUE TITLE
Rename the package to `SDL.jl`?

### ISSUE THREAD

**Issue by Gnimuc** [JuliaMultimedia/SimpleDirectMediaLayer.jl#56]
"SDL" is famous than its full name "Simple DirectMedia Layer". I'd heard of "SDL" before but it is until I saw this package that I knew the real name of `SDL`...

**Comment by Gnimuc** [comment]
@aviks as you're the only user, so if you're OK, then I'm gonna make the change and tag a new release.

**Comment by aviks** [comment]
Note that the name SDL.jl will fall foul of the general registry naming guidelines.

**Comment by Gnimuc** [comment]
I don't think the guideline should apply to a wrapper package. The name of a JLL package should be exactly the same as the C/C++ library, so the same rule should be used for the wrapper package too. The reason why this package is named as "SimpleDirectMediaLayer.jl" is probably historical: there was a unmaintained https://github.com/ariejdl/SDL.jl in the old registry.

**Comment by Gnimuc** [comment]
Another example is https://github.com/zyedidia/SFML.jl, the old registry accepted that name as well.
