### ISSUE TITLE
Mix_LoadWAV seems to be missing 

### ISSUE THREAD

**Issue by aviks** [JuliaMultimedia/SimpleDirectMediaLayer.jl#58]
https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC19

**Comment by aviks** [comment]
`Mix_LoadWAV_RW` is present. 

Also, `Mix_PlayChannel` seems to be missing, though `Mix_PlayChannelTimed` is present. In either case the missing functions are a thin wrapper around the function that exists (if that helps)

cc: @Gnimuc

**Comment by Gnimuc** [comment]
`Mix_LoadWAV` and ` Mix_PlayChannel` are both helper macros that should be manually implemented on the Julia side.
