### ISSUE TITLE
Example from README.md does not work

### ISSUE THREAD

**Issue by ufechner7** [JuliaMultimedia/SimpleDirectMediaLayer.jl#63]
I tried the latest version of SimpleDirectMediaLayer. When I try to run the example I only get a black Window and a lot of warnings in the console.
`ALSA lib conf.c:4499:(snd_config_update_r) Cannot access file /workspace/destdir/share/alsa/alsa.conf`

Ubuntu 18.04, Julia 1.7

**Comment by dustyirwin** [comment]
I get the a black window as well. The AWSD keys are unresponsive. 

Windows 10, Julia1.8

**Comment by aviks** [comment]
On linux, the ALSA issues can be worked around by: https://github.com/JuliaPackaging/Yggdrasil/issues/1432#issuecomment-851065063

As to the example code in the home directory, it expects  a PNG file at a certain location:  `surface = IMG_Load(joinpath(@__DIR__, "..", "assets", "cat.png"))` 

So it's best to run the file from the [examples](https://github.com/JuliaMultimedia/SimpleDirectMediaLayer.jl/tree/master/examples) directory. I just ran this, and without the png file in the correct location, you'll just see a black screen. With the file, things seem to work fine.
